apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: opentelemetry-operator-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: opentelemetry-operator-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy